### ISSUE TITLE
Working great on windows 10 but not on linux

### ISSUE THREAD

**Issue by JackMD** [CharlotteDunois/Yasmin#106]
### Description
So I have the following in `Start.php` file:

```php
<?php

use CharlotteDunois\Yasmin\Client;
use React\EventLoop\Factory;

require(__DIR__ . '/vendor/autoload.php');

$loop = Factory::create();
$client = new Client([], $loop);

echo "Starting\n";

$client->on('ready', function() use ($client){
	echo 'Successfully logged into ' . $client->user->tag . PHP_EOL;
});

$client->login('token-here')->done();
$loop->run();
```

Composer and everything is configured properly and found working.

### Details

PHP Version: 7.2
OS: Linux Ubuntu 18.04

### Additional Details

This file when executed on windows 10 works fine and the bot goes online. However when the same file is executed on ubuntu vps then the bot never goes online its like the loop never runs.

**Comment by CharlotteDunois** [comment]
The provided MCVE works for me without any issues on Debian Jessie. Make sure that OpenSSL is working correctly (maybe try <https://github.com/CharlotteDunois/Yasmin#windows-and-ssl>?).

You can further debug Yasmin by listening to the `debug` event:
```php
$client->on('debug', function ($msg) {
    echo $msg.PHP_EOL;
});
```

**Comment by JackMD** [comment]
Ok I will try debugging.

**Comment by JackMD** [comment]
```
Adding request "gateway/bot" to ratelimit bucket
Retrieved item from bucket "gateway"
Executing item "gateway/bot"
Request for item "gateway/bot" failed with exception RuntimeException
```

Adding debug produced the following result. I have yet to try OpenSSL

**Comment by JackMD** [comment]
I checked ssl. its working corretly. I also tried setting path to ca file but still no good.

```
Retrieved item from bucket "gateway"
Executing item "gateway/bot"
Got response for item "gateway/bot" with HTTP status code 200
Request for item "gateway/bot" failed with exception Error
```

**Comment by CharlotteDunois** [comment]
Since the last message mentions `Error`, you should've seen an uncaught exception in your console. Since you did not, please make sure the following is true:

- the PHP binary you use to run the script is **minimum** 7.1 - if you use `php Start.php`, run `php -v`
- `display_errors` is set to `On` using `php -i | grep display_errors`
- `error_reporting` is set to `E_ALL` or `-1` using `php -i | grep error_reporting`

**Comment by JackMD** [comment]
`php -v`:
```
PHP 7.3.5-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: May  3 2019 10:00:24) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.5, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.5-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
```

`php -i | grep display_errors`:
```
display_errors => STDOUT => STDOUT
```

`php -i | grep error_reporting`
```
error_reporting => 32767 => 32767
```

**Comment by JackMD** [comment]
Quick update:

I started listening to this
```php
$client->on("error", function(\Throwable $error){
	echo $error->getMessage() . PHP_EOL;
});
```

![image](https://user-images.githubusercontent.com/32965703/58042771-fdfa0100-7b54-11e9-865a-c4e502be196a.png)

The following error was reported.

**Comment by JackMD** [comment]
This is my Start.php script.

```php
<?php

use CharlotteDunois\Yasmin\Client;
use React\EventLoop\Factory;

require(__DIR__ . '/vendor/autoload.php');

$loop = Factory::create();
$client = new Client([], $loop);

echo "Starting\n";

$client->on('ready', function() use ($client){
	echo 'Successfully logged into ' . $client->user->tag . PHP_EOL;
});

$client->on('debug', function($message){
	echo $message . PHP_EOL;
});

$client->on("error", function(\Throwable $error){
	echo $error->getMessage() . PHP_EOL;
});

$client->login('token');
$loop->run();
```

**Comment by JackMD** [comment]
```
Error: Call to undefined function bcadd() in /home/jack/discord/php/test/vendor/charlottedunois/yasmin/src/HTTP/APIManager.php:460
Stack trace:
#0 /home/jack/discord/php/test/vendor/charlottedunois/yasmin/src/HTTP/APIManager.php(474): CharlotteDunois\Yasmin\HTTP\APIManager->extractRatelimit(Object(RingCentral\Psr7\Response))
#1 /home/jack/discord/php/test/vendor/charlottedunois/yasmin/src/HTTP/APIRequest.php(187): CharlotteDunois\Yasmin\HTTP\APIManager->handleRatelimit(Object(RingCentral\Psr7\Response), Object(CharlotteDunois\Yasmin\HTTP\RatelimitBucket), false)
#2 /home/jack/discord/php/test/vendor/react/promise/src/FulfilledPromise.php(25): CharlotteDunois\Yasmin\HTTP\APIRequest->CharlotteDunois\Yasmin\HTTP\{closure}(Object(RingCentral\Psr7\Response))
#3 /home/jack/discord/php/test/vendor/react/promise/src/Promise.php(134): React\Promise\FulfilledPromise->then(Object(Closure), NULL)
#4 /home/jack/discord/php/test/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#5 /home/jack/discord/php/test/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#6 /home/jack/discord/php/test/vendor/react/promise/src/FulfilledPromise.php(39): React\Promise\Promise::React\Promise\{closure}(Object(RingCentral\Psr7\Response))
#7 /home/jack/discord/php/test/vendor/react/promise/src/Promise.php(135): React\Promise\FulfilledPromise->done(Object(Closure), Object(Closure), Object(Closure))
#8 /home/jack/discord/php/test/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#9 /home/jack/discord/php/test/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#10 /home/jack/discord/php/test/vendor/react/promise-timer/src/functions.php(31): React\Promise\Promise::React\Promise\{closure}(Object(RingCentral\Psr7\Response))
#11 /home/jack/discord/php/test/vendor/react/promise/src/FulfilledPromise.php(25): React\Promise\Timer\{closure}(Object(RingCentral\Psr7\Response))
#12 /home/jack/discord/php/test/vendor/react/promise/src/Promise.php(134): React\Promise\FulfilledPromise->then(Object(Closure), Object(Closure))
#13 /home/jack/discord/php/test/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#14 /home/jack/discord/php/test/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#15 /home/jack/discord/php/test/vendor/react/promise/src/Deferred.php(36): React\Promise\Promise::React\Promise\{closure}(Object(RingCentral\Psr7\Response))
#16 /home/jack/discord/php/test/vendor/react/promise/src/FulfilledPromise.php(25): React\Promise\Deferred->resolve(Object(RingCentral\Psr7\Response))
#17 /home/jack/discord/php/test/vendor/react/promise/src/Promise.php(134): React\Promise\FulfilledPromise->then(Array, Array)
#18 /home/jack/discord/php/test/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#19 /home/jack/discord/php/test/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#20 /home/jack/discord/php/test/vendor/react/promise/src/FulfilledPromise.php(39): React\Promise\Promise::React\Promise\{closure}(Object(RingCentral\Psr7\Response))
#21 /home/jack/discord/php/test/vendor/react/promise/src/Promise.php(135): React\Promise\FulfilledPromise->done(Object(Closure), Object(Closure), Object(Closure))
#22 /home/jack/discord/php/test/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#23 /home/jack/discord/php/test/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#24 /home/jack/discord/php/test/vendor/react/promise/src/FulfilledPromise.php(39): React\Promise\Promise::React\Promise\{closure}(Object(RingCentral\Psr7\Response))
#25 /home/jack/discord/php/test/vendor/react/promise/src/Promise.php(66): React\Promise\FulfilledPromise->done(Object(Closure), Object(Closure))
#26 /home/jack/discord/php/test/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#27 /home/jack/discord/php/test/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#28 /home/jack/discord/php/test/vendor/react/promise/src/FulfilledPromise.php(39): React\Promise\Promise::React\Promise\{closure}(Object(RingCentral\Psr7\Response))
#29 /home/jack/discord/php/test/vendor/react/promise/src/Promise.php(135): React\Promise\FulfilledPromise->done(Object(Closure), Object(Closure), Object(Closure))
#30 /home/jack/discord/php/test/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#31 /home/jack/discord/php/test/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#32 /home/jack/discord/php/test/vendor/react/promise/src/FulfilledPromise.php(39): React\Promise\Promise::React\Promise\{closure}('{"url": "wss://...')
#33 /home/jack/discord/php/test/vendor/react/promise/src/Promise.php(135): React\Promise\FulfilledPromise->done(Object(Closure), Object(Closure), Object(Closure))
#34 /home/jack/discord/php/test/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#35 /home/jack/discord/php/test/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#36 /home/jack/discord/php/test/vendor/react/promise-stream/src/functions.php(43): React\Promise\Promise::React\Promise\{closure}('{"url": "wss://...')
#37 /home/jack/discord/php/test/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\Promise\Stream\{closure}()
#38 /home/jack/discord/php/test/vendor/clue/buzz-react/src/Message/ReadableBodyStream.php(44): Evenement\EventEmitter->emit('close')
#39 /home/jack/discord/php/test/vendor/clue/buzz-react/src/Message/ReadableBodyStream.php(33): Clue\React\Buzz\Message\ReadableBodyStream->close()
#40 /home/jack/discord/php/test/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): Clue\React\Buzz\Message\ReadableBodyStream->Clue\React\Buzz\Message\{closure}()
#41 /home/jack/discord/php/test/vendor/react/http-client/src/Response.php(107): Evenement\EventEmitter->emit('end')
#42 /home/jack/discord/php/test/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\HttpClient\Response->handleEnd()
#43 /home/jack/discord/php/test/vendor/react/http-client/src/ChunkedStreamDecoder.php(108): Evenement\EventEmitter->emit('end')
#44 /home/jack/discord/php/test/vendor/react/http-client/src/ChunkedStreamDecoder.php(68): React\HttpClient\ChunkedStreamDecoder->iterateBuffer()
#45 /home/jack/discord/php/test/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\HttpClient\ChunkedStreamDecoder->handleData('83\r\n{"url": "ws...')
#46 /home/jack/discord/php/test/vendor/react/http-client/src/Request.php(169): Evenement\EventEmitter->emit('data', Array)
#47 /home/jack/discord/php/test/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\HttpClient\Request->handleData('HTTP/1.1 200 OK...')
#48 /home/jack/discord/php/test/vendor/react/stream/src/Util.php(71): Evenement\EventEmitter->emit('data', Array)
#49 /home/jack/discord/php/test/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\Stream\Util::React\Stream\{closure}('HTTP/1.1 200 OK...')
#50 /home/jack/discord/php/test/vendor/react/stream/src/DuplexResourceStream.php(193): Evenement\EventEmitter->emit('data', Array)
#51 /home/jack/discord/php/test/vendor/react/event-loop/src/StreamSelectLoop.php(244): React\Stream\DuplexResourceStream->handleData(Resource id #231)
#52 /home/jack/discord/php/test/vendor/react/event-loop/src/StreamSelectLoop.php(211): React\EventLoop\StreamSelectLoop->waitForStreamActivity(54950610)
#53 /home/jack/discord/php/test/Test.php(26): React\EventLoop\StreamSelectLoop->run()
#54 {main}
```

Full stack trace.

**Comment by CharlotteDunois** [comment]
`bcmath` is required as dependency by composer (see composer.json). If you installed it through a different binary where bcmath is loaded, then you've just bypassed the check. Otherwise it would be a bug in composer, however the former is a much more likely case.

Long story short: Install and enable the bcmath extension.

**Comment by JackMD** [comment]
Error fixed. Bot is now working. bc-math extension was missing

**Comment by JackMD** [comment]
Sorry for wasting your time. Just wanted to say one more thing, This library is great! Thanks for sharing it.
