### ISSUE TITLE
GuildMemberStorage throws TypeError upon using the "filter" method

### ISSUE THREAD

**Issue by sylae** [CharlotteDunois/Yasmin#64]
**Please describe the issue you are having:**
Using the `filter` method on a GuildMemberStorage results in a TypeError. From some research it appears to be caused by the object using the generic method provided by Storage. I *think* overriding it in GuildMemberStorage with the following will do the trick:

```php
    /**
     * {@inheritdoc}
     * @param callable  $closure
     * @return \CharlotteDunois\Yasmin\Interfaces\StorageInterface
    */
    function filter(callable $closure) {
        $col = parent::filter($closure);
        return (new static($this->client, $this->guild, $col->all()));
    }
```

**If you are encountering any errors, post the full stack trace here:**
```
// shown below
```

**Please include a Minimal, Complete and Verifiable Example:**
```php
<?php
require_once "vendor/autoload.php";
$loop = \React\EventLoop\Factory::create();
$client = new \CharlotteDunois\Yasmin\Client(array(), $loop);

$client->on('ready', function () use ($client) {
    echo 'Logged in as '.$client->user->tag.' created on '.$client->user->createdAt->format('d.m.Y H:i:s').PHP_EOL;
});

$client->on('message', function ($message) {
  return $message->guild->members->filter(function($v, $k) {
    return true; // or whatever really
  });
});

$client->login('token')->done();
$loop->run();
```

**Please include the expected output of the MCVE:**
```php
// not throwing an error
```

**Please include the actual output of the MCVE:**
```php
Logged in as Huntress#7113 created on 01.05.2018 11:08:50
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to CharlotteDunois\Yasmin\Models\GuildMemberStorage::__construct() must be an instance of CharlotteDunois\Yasmin\Models\Guild, array given, called in C:\Users\Sylae\Documents\GitHub\test\vendor\charlottedunois\yasmin\src\Models\Storage.php on line 181 and defined in C:\Users\Sylae\Documents\GitHub\test\vendor\charlottedunois\yasmin\src\Models\GuildMemberStorage.php:25
Stack trace:
#0 C:\Users\Sylae\Documents\GitHub\test\vendor\charlottedunois\yasmin\src\Models\Storage.php(181): CharlotteDunois\Yasmin\Models\GuildMemberStorage->__construct(Object(CharlotteDunois\Yasmin\Client), Array)
#1 C:\Users\Sylae\Documents\GitHub\test\test.php(13): CharlotteDunois\Yasmin\Models\Storage->filter(Object(Closure))
#2 C:\Users\Sylae\Documents\GitHub\test\vendor\charlottedunois\eventemitter\src\EventEmitterErrorTrait.php(35): {closure}(Object(CharlotteDunois\Yasmin\Models\Message))
#3 C:\Users\Sylae\Documents\GitHub\test\vendor\charlottedunois\yasmin\src\Client.php(284): CharlotteDunois\Ya in C:\Users\Sylae\Documents\GitHub\test\vendor\charlottedunois\yasmin\src\Models\GuildMemberStorage.php on line 25

Fatal error: Uncaught TypeError: Argument 2 passed to CharlotteDunois\Yasmin\Models\GuildMemberStorage::__construct() must be an instance of CharlotteDunois\Yasmin\Models\Guild, array given, called in C:\Users\Sylae\Documents\GitHub\test\vendor\charlottedunois\yasmin\src\Models\Storage.php on line 181 and defined in C:\Users\Sylae\Documents\GitHub\test\vendor\charlottedunois\yasmin\src\Models\GuildMemberStorage.php on line 25

TypeError: Argument 2 passed to CharlotteDunois\Yasmin\Models\GuildMemberStorage::__construct() must be an instance of CharlotteDunois\Yasmin\Models\Guild, array given, called in C:\Users\Sylae\Documents\GitHub\test\vendor\charlottedunois\yasmin\src\Models\Storage.php on line 181 in C:\Users\Sylae\Documents\GitHub\test\vendor\charlottedunois\yasmin\src\Models\GuildMemberStorage.php on line 25

Call Stack:
    0.4030     407536   1. {main}() C:\Users\Sylae\Documents\GitHub\test\test.php:0
    0.7190    4730704   2. React\EventLoop\StreamSelectLoop->run() C:\Users\Sylae\Documents\GitHub\test\test.php:17
   48.3240   11508016   3. React\EventLoop\Timer\Timers->tick() C:\Users\Sylae\Documents\GitHub\test\vendor\react\event-loop\src\StreamSelectLoop.php:177
   48.3240   11507992   4. CharlotteDunois\Yasmin\Client->CharlotteDunois\Yasmin\{closure}() C:\Users\Sylae\Documents\GitHub\test\vendor\react\event-loop\src\Timer\Timers.php:89
   48.3240   11507992   5. CharlotteDunois\Yasmin\WebSocket\Events\Ready->CharlotteDunois\Yasmin\WebSocket\Events\{closure}() C:\Users\Sylae\Documents\GitHub\test\vendor\charlottedunois\yasmin\src\Client.php:870
   48.3240   11507992   6. CharlotteDunois\Yasmin\WebSocket\WSManager->emit() C:\Users\Sylae\Documents\GitHub\test\vendor\charlottedunois\yasmin\src\WebSocket\Events\Ready.php:69
   48.3240   11508048   7. CharlotteDunois\Yasmin\WebSocket\WSManager->CharlotteDunois\Yasmin\WebSocket\{closure}() C:\Users\Sylae\Documents\GitHub\test\vendor\charlottedunois\eventemitter\src\EventEmitterTrait.php:149
   48.3240   11508048   8. CharlotteDunois\Yasmin\WebSocket\WSManager->emit() C:\Users\Sylae\Documents\GitHub\test\vendor\charlottedunois\yasmin\src\WebSocket\WSManager.php:164
   48.3240   11507120   9. CharlotteDunois\Yasmin\Client->CharlotteDunois\Yasmin\{closure}() C:\Users\Sylae\Documents\GitHub\test\vendor\charlottedunois\eventemitter\src\EventEmitterTrait.php:158
   48.3240   11475776  10. CharlotteDunois\Yasmin\Client->emit() C:\Users\Sylae\Documents\GitHub\test\vendor\charlottedunois\yasmin\src\Client.php:284
   48.3240   11476152  11. {closure:C:\Users\Sylae\Documents\GitHub\test\test.php:10-14}() C:\Users\Sylae\Documents\GitHub\test\vendor\charlottedunois\eventemitter\src\EventEmitterErrorTrait.php:35
   48.3240   11476472  12. CharlotteDunois\Yasmin\Models\GuildMemberStorage->filter() C:\Users\Sylae\Documents\GitHub\test\test.php:13
   48.3240   11484944  13. CharlotteDunois\Yasmin\Models\GuildMemberStorage->__construct() C:\Users\Sylae\Documents\GitHub\test\vendor\charlottedunois\yasmin\src\Models\Storage.php:181

```

**Further details:**

- Yasmin version: tested on 1087e245158e369abc241f9c5ea6423337116e48 and 0ad8f2551bffcdf69ab61968360583e015d041cb
- PHP version: 7.2.10
- Operating System: tested on Win7x64 and debian 9.5 amd64

- [x] I have also tested the issue on latest master with commit hash: 1087e245158e369abc241f9c5ea6423337116e48

**Comment by CharlotteDunois** [comment]
Thanks for reporting this bug! This will be fixed in the next patch version.
