### ISSUE TITLE
Reconnection gets stopped

### ISSUE THREAD

**Issue by CharlotteDunois** [CharlotteDunois/Yasmin#74]
**Please describe the issue you are having:**
Reconnection does not seem to be continued to happen after the DNS query fails. Additionally there seems to be an error where we don't receive a `WSConnection` instance but null in the Client.

**If you are encountering any errors, post the full stack trace here:**
WS Connection errors:
```
27.11.2018, 08:53:15.860 - [error]: Connection closed before handshake
27.11.2018, 08:53:15.876 - [debug]: TypeError: Argument 1 passed to CharlotteDunois\Yasmin\Client::CharlotteDunois\Yasmin\{closure}() must be an instance of CharlotteDunois\Yasmin\WebSocket\WSConnection, null given, called in /var/opt/AhriBot/vendor/react/promise/src/FulfilledPromise.php on line 25 and defined in /var/opt/AhriBot/vendor/charlottedunois/yasmin/src/Client.php:544
Stack trace:
#0 /var/opt/AhriBot/vendor/react/promise/src/FulfilledPromise.php(25): CharlotteDunois\Yasmin\Client->CharlotteDunois\Yasmin\{closure}(NULL)
#1 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(134): React\Promise\FulfilledPromise->then(Object(Closure), NULL)
#2 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#3 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#4 [internal function]: React\Promise\Promise::React\Promise\{closure}(NULL)
#5 /var/opt/AhriBot/vendor/react/promise/src/Deferred.php(36): call_user_func(Object(Closure), NULL)
#6 /var/opt/AhriBot/vendor/charlottedunois/yasmin/src/WebSocket/WSConnection.php(265): React\Promise\Deferred->resolve()
#7 /var/opt/AhriBot/vendor/react/promise/src/FulfilledPromise.php(39): CharlotteDunois\Yasmin\WebSocket\WSConnection->CharlotteDunois\Yasmin\WebSocket\{closure}(Object(CharlotteDunois\Yasmin\WebSocket\WSConnection))
#8 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(66): React\Promise\FulfilledPromise->done(Object(Closure), Object(Closure))
#9 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#10 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#11 /var/opt/AhriBot/vendor/react/promise/src/FulfilledPromise.php(39): React\Promise\Promise::React\Promise\{closure}(Object(CharlotteDunois\Yasmin\WebSocket\WSConnection))
#12 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(135): React\Promise\FulfilledPromise->done(Object(Closure), Object(Closure), Object(Closure))
#13 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#14 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#15 /var/opt/AhriBot/vendor/react/promise/src/FulfilledPromise.php(39): React\Promise\Promise::React\Promise\{closure}(Object(CharlotteDunois\Yasmin\WebSocket\WSConnection))
#16 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(66): React\Promise\FulfilledPromise->done(Object(Closure), Object(Closure))
#17 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#18 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#19 [internal function]: React\Promise\Promise::React\Promise\{closure}(Object(CharlotteDunois\Yasmin\WebSocket\WSConnection))
#20 /var/opt/AhriBot/vendor/react/promise/src/Deferred.php(36): call_user_func(Object(Closure), Object(CharlotteDunois\Yasmin\WebSocket\WSConnection))
#21 /var/opt/AhriBot/vendor/charlottedunois/yasmin/src/WebSocket/WSConnection.php(580): React\Promise\Deferred->resolve(Object(CharlotteDunois\Yasmin\WebSocket\WSConnection))
#22 /var/opt/AhriBot/vendor/charlottedunois/eventemitter/src/EventEmitterTrait.php(158): CharlotteDunois\Yasmin\WebSocket\WSConnection->CharlotteDunois\Yasmin\WebSocket\{closure}()
#23 /var/opt/AhriBot/vendor/charlottedunois/yasmin/src/WebSocket/Events/Ready.php(47): CharlotteDunois\Yasmin\WebSocket\WSConnection->emit('self.ready')
#24 /var/opt/AhriBot/vendor/charlottedunois/yasmin/src/WebSocket/Handlers/Dispatch.php(79): CharlotteDunois\Yasmin\WebSocket\Events\Ready->handle(Object(CharlotteDunois\Yasmin\WebSocket\WSConnection), Array)
#25 /var/opt/AhriBot/vendor/charlottedunois/yasmin/src/WebSocket/WSHandler.php(81): CharlotteDunois\Yasmin\WebSocket\Handlers\Dispatch->handle(Object(CharlotteDunois\Yasmin\WebSocket\WSConnection), Array)
#26 /var/opt/AhriBot/vendor/charlottedunois/yasmin/src/WebSocket/WSConnection.php(631): CharlotteDunois\Yasmin\WebSocket\WSHandler->handle(Object(CharlotteDunois\Yasmin\WebSocket\WSConnection), '{"t":"READY","s...')
#27 /var/opt/AhriBot/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): CharlotteDunois\Yasmin\WebSocket\WSConnection->CharlotteDunois\Yasmin\WebSocket\{closure}('{"t":"READY","s...', Object(Ratchet\Client\WebSocket))
#28 /var/opt/AhriBot/vendor/ratchet/pawl/src/WebSocket.php(72): Ratchet\Client\WebSocket->emit('message', Array)
#29 /var/opt/AhriBot/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(104): Ratchet\Client\WebSocket->Ratchet\Client\{closure}(Object(Ratchet\RFC6455\Messaging\Message))
#30 /var/opt/AhriBot/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(60): Ratchet\RFC6455\Messaging\MessageBuffer->processData('\x82~\x01.\x84\x92Mj\xC30\x10\x85\xEF\xA2u...')
#31 /var/opt/AhriBot/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): Ratchet\RFC6455\Messaging\MessageBuffer->onData('\x82~\x01.\x84\x92Mj\xC30\x10\x85\xEF\xA2u...')
#32 /var/opt/AhriBot/vendor/react/stream/src/Util.php(71): Evenement\EventEmitter->emit('data', Array)
#33 /var/opt/AhriBot/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\Stream\Util::React\Stream\{closure}('\x82~\x01.\x84\x92Mj\xC30\x10\x85\xEF\xA2u...')
#34 /var/opt/AhriBot/vendor/react/stream/src/DuplexResourceStream.php(193): Evenement\EventEmitter->emit('data', Array)
#35 /var/opt/AhriBot/vendor/react/event-loop/src/ExtEventLoop.php(251): React\Stream\DuplexResourceStream->handleData(Resource id #515)
#36 [internal function]: React\EventLoop\ExtEventLoop->React\EventLoop\{closure}(Resource id #515, 2, NULL)
#37 /var/opt/AhriBot/vendor/react/event-loop/src/ExtEventLoop.php(189): EventBase->loop(1)
#38 /var/opt/AhriBot/index.php(106): React\EventLoop\ExtEventLoop->run()
#39 {main}
```

DNS errors:
```
Next RuntimeException: Connection to gateway.discord.gg:443 failed during DNS lookup: DNS query for gateway.discord.gg failed: too many retries in /var/opt/AhriBot/vendor/react/socket/src/DnsConnector.php:95
Stack trace:
#0 /var/opt/AhriBot/vendor/react/promise/src/RejectedPromise.php(25): React\Socket\DnsConnector->React\Socket\{closure}(Object(RuntimeException))
#1 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(134): React\Promise\RejectedPromise->then(Object(Closure), Object(Closure))
#2 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\RejectedPromise))
#3 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(148): React\Promise\Promise->settle(Object(React\Promise\RejectedPromise))
#4 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(237): React\Promise\Promise->reject(Object(RuntimeException))
#5 /var/opt/AhriBot/vendor/react/promise/src/RejectedPromise.php(39): React\Promise\Promise::React\Promise\{closure}(Object(RuntimeException))
#6 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(135): React\Promise\RejectedPromise->done(Object(Closure), Object(Closure), Object(Closure))
#7 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\RejectedPromise))
#8 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(148): React\Promise\Promise->settle(Object(React\Promise\RejectedPromise))
#9 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(237): React\Promise\Promise->reject(Object(RuntimeException))
#10 /var/opt/AhriBot/vendor/react/promise/src/RejectedPromise.php(39): React\Promise\Promise::React\Promise\{closure}(Object(RuntimeException))
#11 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(135): React\Promise\RejectedPromise->done(Object(Closure), Object(Closure), Object(Closure))
#12 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\RejectedPromise))
#13 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(148): React\Promise\Promise->settle(Object(React\Promise\RejectedPromise))
#14 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(237): React\Promise\Promise->reject(Object(RuntimeException))
#15 [internal function]: React\Promise\Promise::React\Promise\{closure}(Object(RuntimeException))
#16 /var/opt/AhriBot/vendor/react/promise/src/Deferred.php(43): call_user_func(Object(Closure), Object(RuntimeException))
#17 /var/opt/AhriBot/vendor/react/dns/src/Query/RetryExecutor.php(47): React\Promise\Deferred->reject(Object(RuntimeException))
#18 /var/opt/AhriBot/vendor/react/promise/src/RejectedPromise.php(25): React\Dns\Query\RetryExecutor->React\Dns\Query\{closure}(Object(RuntimeException))
#19 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(134): React\Promise\RejectedPromise->then(Object(Closure), Object(Closure))
#20 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\RejectedPromise))
#21 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(148): React\Promise\Promise->settle(Object(React\Promise\RejectedPromise))
#22 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(237): React\Promise\Promise->reject(Object(React\Dns\Query\TimeoutException))
#23 /var/opt/AhriBot/vendor/react/promise/src/RejectedPromise.php(39): React\Promise\Promise::React\Promise\{closure}(Object(React\Dns\Query\TimeoutException))
#24 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(135): React\Promise\RejectedPromise->done(Object(Closure), Object(Closure), Object(Closure))
#25 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\RejectedPromise))
#26 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(148): React\Promise\Promise->settle(Object(React\Promise\RejectedPromise))
#27 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(237): React\Promise\Promise->reject(Object(React\Promise\Timer\TimeoutException))
#28 /var/opt/AhriBot/vendor/react/promise-timer/src/functions.php(47): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\Timer\TimeoutException))
#29 /var/opt/AhriBot/vendor/react/event-loop/src/ExtEventLoop.php(228): React\Promise\Timer\{closure}(Object(React\EventLoop\Timer\Timer))
#30 [internal function]: React\EventLoop\ExtEventLoop->React\EventLoop\{closure}(-1, 1, Object(React\EventLoop\Timer\Timer))
#31 /var/opt/AhriBot/vendor/react/event-loop/src/ExtEventLoop.php(189): EventBase->loop(1)
#32 /var/opt/AhriBot/index.php(106): React\EventLoop\ExtEventLoop->run()
#33 {main}
```

**Further details:**

- Yasmin version: dev-master
- PHP version: PHP 7.2.12-1+0\~20181112102304.11+stretch\~1.gbp55f215 (cli) (built: Nov 12 2018 10:23:04) ( NTS )
- Operating System: Debian Stretch

- [X] I have also tested the issue on latest master with commit hash: 6b97b54

**Comment by CharlotteDunois** [comment]
Ahri Bot debug log:
```
05.01.2019, 22:35:28.914 - [debug]: Shard 0 has WS heart failure
05.01.2019, 22:35:28.914 - [debug]: Shard 0 disconnecting from WS
05.01.2019, 22:35:28.914 - [debug]: Shard 0 destroyed compress context
05.01.2019, 22:35:28.914 - [debug]: Shard 0 disconnected with code 1006 and reason "No heartbeat ack"
05.01.2019, 22:35:28.914 - [debug]: Yasmin Shard 0 got disconnected from Discord, destroying all shard players...
05.01.2019, 22:35:28.915 - [debug]: Shard 0 using compress context ZlibStream
05.01.2019, 22:35:28.915 - [debug]: Shard 0 connecting to WS wss://gateway.discord.gg/?v=6&encoding=json&compress=zlib-stream
05.01.2019, 22:35:43.923 - [debug]: React\Promise\Timer\TimeoutException: Timed out after 5 seconds in /var/opt/AhriBot/vendor/react/promise-timer/src/functions.php:47
Stack trace:
#0 /var/opt/AhriBot/vendor/react/event-loop/src/ExtEventLoop.php(228): React\Promise\Timer\{closure}(Object(React\EventLoop\Timer\Timer))
#1 [internal function]: React\EventLoop\ExtEventLoop->React\EventLoop\{closure}(-1, 1, Object(React\EventLoop\Timer\Timer))
#2 /var/opt/AhriBot/vendor/react/event-loop/src/ExtEventLoop.php(189): EventBase->loop(1)
#3 /var/opt/AhriBot/index.php(106): React\EventLoop\ExtEventLoop->run()
#4 {main}

Next React\Dns\Query\TimeoutException: DNS query for gateway.discord.gg timed out in /var/opt/AhriBot/vendor/react/dns/src/Query/TimeoutExecutor.php:27
Stack trace:
#0 /var/opt/AhriBot/vendor/react/promise/src/RejectedPromise.php(25): React\Dns\Query\TimeoutExecutor->React\Dns\Query\{closure}(Object(React\Promise\Timer\TimeoutException))
#1 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(134): React\Promise\RejectedPromise->then(NULL, Object(Closure))
#2 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\RejectedPromise))
#3 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(148): React\Promise\Promise->settle(Object(React\Promise\RejectedPromise))
#4 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(237): React\Promise\Promise->reject(Object(React\Promise\Timer\TimeoutException))
#5 /var/opt/AhriBot/vendor/react/promise-timer/src/functions.php(47): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\Timer\TimeoutException))
#6 /var/opt/AhriBot/vendor/react/event-loop/src/ExtEventLoop.php(228): React\Promise\Timer\{closure}(Object(React\EventLoop\Timer\Timer))
#7 [internal function]: React\EventLoop\ExtEventLoop->React\EventLoop\{closure}(-1, 1, Object(React\EventLoop\Timer\Timer))
#8 /var/opt/AhriBot/vendor/react/event-loop/src/ExtEventLoop.php(189): EventBase->loop(1)
#9 /var/opt/AhriBot/index.php(106): React\EventLoop\ExtEventLoop->run()
#10 {main}

Next RuntimeException: DNS query for gateway.discord.gg failed: too many retries in /var/opt/AhriBot/vendor/react/dns/src/Query/RetryExecutor.php:44
Stack trace:
#0 /var/opt/AhriBot/vendor/react/promise/src/RejectedPromise.php(25): React\Dns\Query\RetryExecutor->React\Dns\Query\{closure}(Object(React\Dns\Query\TimeoutException))
#1 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(134): React\Promise\RejectedPromise->then(Object(Closure), Object(Closure))
#2 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\RejectedPromise))
#3 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(148): React\Promise\Promise->settle(Object(React\Promise\RejectedPromise))
#4 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(237): React\Promise\Promise->reject(Object(React\Dns\Query\TimeoutException))
#5 /var/opt/AhriBot/vendor/react/promise/src/RejectedPromise.php(39): React\Promise\Promise::React\Promise\{closure}(Object(React\Dns\Query\TimeoutException))
#6 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(135): React\Promise\RejectedPromise->done(Object(Closure), Object(Closure), Object(Closure))
#7 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\RejectedPromise))
#8 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(148): React\Promise\Promise->settle(Object(React\Promise\RejectedPromise))
#9 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(237): React\Promise\Promise->reject(Object(React\Promise\Timer\TimeoutException))
#10 /var/opt/AhriBot/vendor/react/promise-timer/src/functions.php(47): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\Timer\TimeoutException))
#11 /var/opt/AhriBot/vendor/react/event-loop/src/ExtEventLoop.php(228): React\Promise\Timer\{closure}(Object(React\EventLoop\Timer\Timer))
#12 [internal function]: React\EventLoop\ExtEventLoop->React\EventLoop\{closure}(-1, 1, Object(React\EventLoop\Timer\Timer))
#13 /var/opt/AhriBot/vendor/react/event-loop/src/ExtEventLoop.php(189): EventBase->loop(1)
#14 /var/opt/AhriBot/index.php(106): React\EventLoop\ExtEventLoop->run()
#15 {main}

Next RuntimeException: Connection to gateway.discord.gg:443 failed during DNS lookup: DNS query for gateway.discord.gg failed: too many retries in /var/opt/AhriBot/vendor/react/socket/src/DnsConnector.php:95
Stack trace:
#0 /var/opt/AhriBot/vendor/react/promise/src/RejectedPromise.php(25): React\Socket\DnsConnector->React\Socket\{closure}(Object(RuntimeException))
#1 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(134): React\Promise\RejectedPromise->then(Object(Closure), Object(Closure))
#2 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\RejectedPromise))
#3 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(148): React\Promise\Promise->settle(Object(React\Promise\RejectedPromise))
#4 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(237): React\Promise\Promise->reject(Object(RuntimeException))
#5 /var/opt/AhriBot/vendor/react/promise/src/RejectedPromise.php(39): React\Promise\Promise::React\Promise\{closure}(Object(RuntimeException))
#6 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(135): React\Promise\RejectedPromise->done(Object(Closure), Object(Closure), Object(Closure))
#7 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\RejectedPromise))
#8 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(148): React\Promise\Promise->settle(Object(React\Promise\RejectedPromise))
#9 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(237): React\Promise\Promise->reject(Object(RuntimeException))
#10 /var/opt/AhriBot/vendor/react/promise/src/RejectedPromise.php(39): React\Promise\Promise::React\Promise\{closure}(Object(RuntimeException))
#11 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(135): React\Promise\RejectedPromise->done(Object(Closure), Object(Closure), Object(Closure))
#12 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\RejectedPromise))
#13 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(148): React\Promise\Promise->settle(Object(React\Promise\RejectedPromise))
#14 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(237): React\Promise\Promise->reject(Object(RuntimeException))
#15 [internal function]: React\Promise\Promise::React\Promise\{closure}(Object(RuntimeException))
#16 /var/opt/AhriBot/vendor/react/promise/src/Deferred.php(43): call_user_func(Object(Closure), Object(RuntimeException))
#17 /var/opt/AhriBot/vendor/react/dns/src/Query/RetryExecutor.php(47): React\Promise\Deferred->reject(Object(RuntimeException))
#18 /var/opt/AhriBot/vendor/react/promise/src/RejectedPromise.php(25): React\Dns\Query\RetryExecutor->React\Dns\Query\{closure}(Object(RuntimeException))
#19 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(134): React\Promise\RejectedPromise->then(Object(Closure), Object(Closure))
#20 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\RejectedPromise))
#21 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(148): React\Promise\Promise->settle(Object(React\Promise\RejectedPromise))
#22 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(237): React\Promise\Promise->reject(Object(React\Dns\Query\TimeoutException))
#23 /var/opt/AhriBot/vendor/react/promise/src/RejectedPromise.php(39): React\Promise\Promise::React\Promise\{closure}(Object(React\Dns\Query\TimeoutException))
#24 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(135): React\Promise\RejectedPromise->done(Object(Closure), Object(Closure), Object(Closure))
#25 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\RejectedPromise))
#26 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(148): React\Promise\Promise->settle(Object(React\Promise\RejectedPromise))
#27 /var/opt/AhriBot/vendor/react/promise/src/Promise.php(237): React\Promise\Promise->reject(Object(React\Promise\Timer\TimeoutException))
#28 /var/opt/AhriBot/vendor/react/promise-timer/src/functions.php(47): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\Timer\TimeoutException))
#29 /var/opt/AhriBot/vendor/react/event-loop/src/ExtEventLoop.php(228): React\Promise\Timer\{closure}(Object(React\EventLoop\Timer\Timer))
#30 [internal function]: React\EventLoop\ExtEventLoop->React\EventLoop\{closure}(-1, 1, Object(React\EventLoop\Timer\Timer))
#31 /var/opt/AhriBot/vendor/react/event-loop/src/ExtEventLoop.php(189): EventBase->loop(1)
#32 /var/opt/AhriBot/index.php(106): React\EventLoop\ExtEventLoop->run()
#33 {main}
05.01.2019, 22:35:43.923 - [debug]: Adding request "gateway" to ratelimit bucket
05.01.2019, 22:35:43.924 - [debug]: Retrieved item from bucket "gateway"
05.01.2019, 22:35:43.924 - [debug]: Executing item "gateway"
05.01.2019, 22:35:58.932 - [debug]: Shard 0 errored (Connection to discordapp.com:443 failed during DNS lookup: DNS query for discordapp.com failed: too many retries) on making new login after failed connection attempt... retrying in 30 seconds
05.01.2019, 22:36:28.932 - [debug]: Adding request "gateway" to ratelimit bucket
05.01.2019, 22:36:28.932 - [debug]: Retrieved item from bucket "gateway"
05.01.2019, 22:36:28.933 - [debug]: Executing item "gateway"
05.01.2019, 22:37:28.935 - [debug]: Shard 0 errored (Connection to tls://discordapp.com:443 timed out after 60 seconds) on making new login after failed connection attempt... retrying in 30 seconds
05.01.2019, 22:37:58.939 - [debug]: Adding request "gateway" to ratelimit bucket
07.01.2019, 04:52:31.260 - [debug]: Registered type boolean
```

Ahri regular log:
```
05.01.2019, 22:35:28.915 - [warn]: Disconnected! (Shard: 0 | Code: 1006 | Reason: No heartbeat ack)
05.01.2019, 22:35:28.915 - [info]: Reconnecting...
05.01.2019, 22:35:43.923 - [error]: Connection to gateway.discord.gg:443 failed during DNS lookup: DNS query for gateway.discord.gg failed: too many retries
05.01.2019, 22:45:41.385 - [info]: Starting user cleanup
[event loop kept running]
```

**Comment by CharlotteDunois** [comment]
I have not met any such issues again and as such I'm viewing this issue as solved.
